Fix compilation error (#9)
I was compiling pbzx on GNU/Linux, using Clang 21 and/or GCC 15:
```
pbzx.c:77:52: error: expected identifier
   77 |         if      (strcmp(argv[i], "-")  == 0) opts->stdin = true;
      |                                                    ^
/usr/include/stdio.h:66:16: note: expanded from macro 'stdin'
   66 | #define stdin  (stdin)
      |                ^
```
`stdin` is expanded as a standard macro, causing compilation to fail.

This PR changes `option::stdin` to `option::read_stdin`.

PS: Besides this fix, I had to link in additional libraries, via `-lxar
-lbz2 -lxml2 -lssl -lcrypto -lz -llzma`.

Edit: The additional link libraries were due to me linking static
libraries. For dynamic libraries these are not required.

---------

Co-authored-by: Niklas Rosenstein <rosensteinniklas@gmail.com>
Co-authored-by: Claude Opus 4.6 <noreply@anthropic.com>